// swing/watchlist.ts

export interface WatchlistStock {
  symbol: string;
  name: string;
  sector: string;
}

export const SWING_WATCHLIST: WatchlistStock[] = [
  { symbol: 'NSE:RELIANCE-EQ', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'NSE:TCS-EQ', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'NSE:INFY-EQ', name: 'Infosys', sector: 'IT' },
  { symbol: 'NSE:HDFCBANK-EQ', name: 'HDFC Bank', sector: 'Financials' },
  { symbol: 'NSE:ICICIBANK-EQ', name: 'ICICI Bank', sector: 'Financials' },
  { symbol: 'NSE:SBIN-EQ', name: 'State Bank of India', sector: 'Financials' },
  { symbol: 'NSE:AXISBANK-EQ', name: 'Axis Bank', sector: 'Financials' },
  { symbol: 'NSE:KOTAKBANK-EQ', name: 'Kotak Mahindra Bank', sector: 'Financials' },
  { symbol: 'NSE:BAJFINANCE-EQ', name: 'Bajaj Finance', sector: 'Financials' },
  { symbol: 'NSE:LT-EQ', name: 'Larsen & Toubro', sector: 'Capital Goods' },
  { symbol: 'NSE:BHARTIARTL-EQ', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'NSE:TATASTEEL-EQ', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'NSE:JSWSTEEL-EQ', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'NSE:HINDALCO-EQ', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'NSE:M&M-EQ', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'NSE:TATAMOTORS-EQ', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'NSE:MARUTI-EQ', name: 'Maruti Suzuki India', sector: 'Auto' },
  { symbol: 'NSE:SUNPHARMA-EQ', name: 'Sun Pharmaceutical Industries', sector: 'Pharma' },
  { symbol: 'NSE:CIPLA-EQ', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'NSE:ITC-EQ', name: 'ITC', sector: 'FMCG' },
  { symbol: 'NSE:HINDUNILVR-EQ', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'NSE:ADANIENT-EQ', name: 'Adani Enterprises', sector: 'Conglomerates' },
  { symbol: 'NSE:ADANIPORTS-EQ', name: 'Adani Ports & SEZ', sector: 'Infrastructure' },
  { symbol: 'NSE:POWERGRID-EQ', name: 'Power Grid Corp', sector: 'Utilities' },
  { symbol: 'NSE:NTPC-EQ', name: 'NTPC', sector: 'Utilities' },
  { symbol: 'NSE:ONGC-EQ', name: 'Oil & Natural Gas Corp', sector: 'Energy' },
  { symbol: 'NSE:COALINDIA-EQ', name: 'Coal India', sector: 'Energy' },
  { symbol: 'NSE:TRENT-EQ', name: 'Trent', sector: 'Retail' },
  { symbol: 'NSE:DLF-EQ', name: 'DLF', sector: 'Real Estate' },
  { symbol: 'NSE:HAL-EQ', name: 'Hindustan Aeronautics', sector: 'Defense' },
  { symbol: 'NSE:BEL-EQ', name: 'Bharat Electronics', sector: 'Defense' },
  { symbol: 'NSE:PFC-EQ', name: 'Power Finance Corp', sector: 'Financials' },
  { symbol: 'NSE:RECLTD-EQ', name: 'REC Limited', sector: 'Financials' },
  { symbol: 'NSE:POLYCAB-EQ', name: 'Polycab India', sector: 'Capital Goods' },
  { symbol: 'NSE:SIEMENS-EQ', name: 'Siemens', sector: 'Capital Goods' },
  { symbol: 'NSE:ABB-EQ', name: 'ABB India', sector: 'Capital Goods' },
  { symbol: 'NSE:TITAN-EQ', name: 'Titan Company', sector: 'Consumer Goods' },
  { symbol: 'NSE:ASIANPAINT-EQ', name: 'Asian Paints', sector: 'Consumer Goods' },
  { symbol: 'NSE:PIDILITIND-EQ', name: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'NSE:WIPRO-EQ', name: 'Wipro', sector: 'IT' },
  { symbol: 'NSE:HCLTECH-EQ', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'NSE:TVSMOTOR-EQ', name: 'TVS Motor Company', sector: 'Auto' },
  { symbol: 'NSE:EICHERMOT-EQ', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'NSE:ASHOKLEY-EQ', name: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'NSE:DABUR-EQ', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'NSE:BRITANNIA-EQ', name: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'NSE:GODREJPROP-EQ', name: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'NSE:LUPIN-EQ', name: 'Lupin', sector: 'Pharma' },
  { symbol: 'NSE:BIOCON-EQ', name: 'Biocon', sector: 'Pharma' },
  { symbol: 'NSE:TATACHEM-EQ', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'NSE:CONCOR-EQ', name: 'Container Corp of India', sector: 'Infrastructure' },
  { symbol: 'NSE:DIVISLAB-EQ', name: 'Divis Laboratories', sector: 'Pharma' },
  { symbol: 'NSE:DRREDDY-EQ', name: 'Dr Reddys Laboratories', sector: 'Pharma' },
  { symbol: 'NSE:APOLLOHOSP-EQ', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'NSE:AUROPHARMA-EQ', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'NSE:BALKRISIND-EQ', name: 'Balkrishna Industries', sector: 'Auto' },
  { symbol: 'NSE:BHARATFORG-EQ', name: 'Bharat Forge', sector: 'Metals' },
  { symbol: 'NSE:BPCL-EQ', name: 'Bharat Petroleum', sector: 'Energy' },
  { symbol: 'NSE:COLPAL-EQ', name: 'Colgate Palmolive India', sector: 'FMCG' },
  { symbol: 'NSE:CUMMINSIND-EQ', name: 'Cummins India', sector: 'Capital Goods' },
  { symbol: 'NSE:DIXON-EQ', name: 'Dixon Technologies', sector: 'Consumer Durables' },
  { symbol: 'NSE:GRASIM-EQ', name: 'Grasim Industries', sector: 'Cement' },
  { symbol: 'NSE:HAVELLS-EQ', name: 'Havells India', sector: 'Consumer Durables' },
  { symbol: 'NSE:HEROMOTOCO-EQ', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'NSE:IPCALAB-EQ', name: 'Ipca Laboratories', sector: 'Pharma' },
  { symbol: 'NSE:JSWENERGY-EQ', name: 'JSW Energy', sector: 'Utilities' },
  { symbol: 'NSE:LTIM-EQ', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'NSE:MRF-EQ', name: 'MRF', sector: 'Auto' },
  { symbol: 'NSE:NESTLEIND-EQ', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'NSE:OBEROIRLTY-EQ', name: 'Oberoi Realty', sector: 'Real Estate' },
  { symbol: 'NSE:PRESTIGE-EQ', name: 'Prestige Estates Project', sector: 'Real Estate' },
  { symbol: 'NSE:RELIANCE-EQ', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'NSE:TECHM-EQ', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'NSE:ULTRACEMCO-EQ', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NSE:VOLTAS-EQ', name: 'Voltas', sector: 'Consumer Durables' }
];
